version: '3.8'

services:
  rzd-bot:
    build: .
    container_name: rzd-bot
    restart: always  # Если бот упадет или сервер перезагрузится, он встанет сам
    environment:
      # Тут можно переопределить настройки, чтобы не хранить их в коде
      # Но пока берем из application.properties
      - TZ=Europe/Moscow # Важно для корректного времени в логах