spring.application.name=ticket-rzd-tracker

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rzd_tracker}
spring.datasource.username=${DB_USER:tracker_user}
spring.datasource.password=${DB_PASSWORD:tracker_secret_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

bot.name=${BOT_USERNAME}
bot.token=${BOT_TOKEN}

rzd.http.read-timeout-seconds=30
rzd.http.max-retries=3
rzd.http.backoff-base-ms=2000

rzd.proxy.enabled=false
rzd.proxy.host=
rzd.proxy.port=0
rzd.proxy.type=HTTP

rzd.api.base-url=${RZD_BASE_URL:https://ticket.rzd.ru}
rzd.api.main-page-url=${RZD_MAIN_PAGE_URL:${rzd.api.base-url}/}
rzd.api.train-pricing-url=${RZD_TRAIN_PRICING_URL:${rzd.api.base-url}/api/v1/railway-service/prices/train-pricing}
rzd.api.car-pricing-url=${RZD_CAR_PRICING_URL:${rzd.api.base-url}/apib2b/p/Railway/V1/Search/CarPricing?service_provider=B2B_RZD&isBonusPurchase=false}
rzd.api.suggest-url=${RZD_SUGGEST_URL:${rzd.api.base-url}/api/v1/suggests}